package rpi.ws281x;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
import rpi.ws281x.RpiWs281xLibrary.rpi_hw_t;
import rpi.ws281x.RpiWs281xLibrary.ws2811_device;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class ws2811_t extends Structure {
    /** < Timestamp in \u00b5s until which the next render must wait */
    public long render_wait_until;
    /**
     * < Private data for driver use<br>
     * C type : ws2811_device*
     */
    public ws2811_device device;
    /**
     * < RPI Hardware Information<br>
     * C type : const rpi_hw_t*
     */
    public rpi_hw_t rpi_hw;
    /** < Required output frequency */
    public int freq;
    /** < DMA number _not_ already in use */
    public int dmanum;
    /** C type : ws2811_channel_t[RPI_PWM_CHANNELS] */
    public ws2811_channel_t[] channel = new ws2811_channel_t[2];
    public ws2811_t() {
        super();
    }
    protected List<String> getFieldOrder() {
        return Arrays.asList("render_wait_until", "device", "rpi_hw", "freq", "dmanum", "channel");
    }
    /**
     * @param freq < Required output frequency<br>
     * @param dmanum < DMA number _not_ already in use<br>
     * @param channel C type : ws2811_channel_t[RPI_PWM_CHANNELS]
     */
    public ws2811_t(int freq, int dmanum, ws2811_channel_t channel[]) {
        super();
        this.render_wait_until = 0;
        this.device = null;
        this.rpi_hw = null;
        this.freq = freq;
        this.dmanum = dmanum;
        if ((channel.length != this.channel.length))
            throw new IllegalArgumentException("Wrong array size !");
        this.channel = channel;
    }
    public ws2811_t(Pointer peer) {
        super(peer);
    }
    public static class ByReference extends ws2811_t implements Structure.ByReference {

    };
    public static class ByValue extends ws2811_t implements Structure.ByValue {

    };
}
